name: Lint

on:
  push:
    branches:
      - main
  pull_request:

env:
  FORCE_COLOR: "1"

permissions: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false

      - uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5
        with:
          python-version-file: pyproject.toml
          cache: "pip"
          cache-dependency-path: pyproject.toml

      - name: lint
        run: make lint INSTALL_EXTRA=lint
