name: Unit tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        python:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # unit tests use the ambient OIDC credential
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false

      - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5
        with:
          python-version: ${{ matrix.python }}
          cache: "pip"
          cache-dependency-path: pyproject.toml
          allow-prereleases: true

      - name: test
        run: make test INSTALL_EXTRA=test
